name: Export Inventor Files to STEP

on:
  push:
    branches: [ main ]
    paths:
      - '**/*.ipt'
      - '**/*.iam'

jobs:
  export-to-step:
    runs-on: self-hosted
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        lfs: true
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pywin32
        
    - name: Export Inventor files to STEP
      shell: pwsh
      run: |
        # PowerShell script to find and process Inventor files
        $inventorFiles = Get-ChildItem -Path $env:GITHUB_WORKSPACE -Recurse -Include *.ipt,*.iam
        
        foreach ($file in $inventorFiles) {
          Write-Host "Processing $($file.FullName)"
          python $env:GITHUB_WORKSPACE\.github\scripts\export_to_step.py "$($file.FullName)"
        }
        
    - name: Commit STEP files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add *.step
        git commit -m "Export Inventor files to STEP" || echo "No changes to commit"
        git push